version: '3'
services:
  zookeeper:
    image: zookeeper:3.5.8
    container_name: zookeeper_3.5.8
    ports:
      - "2181:2181"
  kafka:
    build: .
    container_name: kafka_2.5.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock